config/routes.rb
RedditRails::Application.routes.draw do
  
  root to: 'pages#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users

  resources :pages, :links
  resources :comments, only: [:create]
  resources :votes, only: [:index, :create]
 

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # attr_accessible :title, :body
  attr_accessible :email, :password, :password_confirmation
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  message    :text
#  user_id    :integer
#  link_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Comment < ActiveRecord::Base

  attr_accessible :message, :link_id, :user_id 

  # Associations --------------------------
  belongs_to :user
  belongs_to :link

end

app/models/link.rb
# == Schema Information
#
# Table name: links
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  title      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  url        :string(255)
#

class Link < ActiveRecord::Base
  attr_accessible :url, :title, :user_id
 
  # Associations -------------------
  belongs_to :user
  has_many :comments
  has_many :votes

  # Validations --------------------
  validates :url, :title, presence: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  email                  :string(255)
#  username               :string(255)
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username, :as => [:admin]
  
  # Associations ---------------------------------
  has_many :links
  has_many :comments
  has_many :votes
end

app/models/vote.rb
# == Schema Information
#
# Table name: votes
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  link_id    :integer
#  up         :boolean
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Vote < ActiveRecord::Base
  attr_accessible :link_id, :up, :user_id

  # Validations ------------------------
  # it cannot save any new votes unless the user_id and link_id combo haven't been taken created before.
  validates :user_id, :uniqueness => { :scope => :link_id } #

  # Associations -----------------------
  belongs_to :user
  belongs_to :link
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  # before_filter :authenticate_user! except: [:index, :contact, :about, :landing, :test]
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # This :authenticat_user! is provide by devise
  # it will redirect user to sign_up path if they
  # are not signed in. It checks to see if user
  # has a valid session
  before_filter :authenticate_user!, only: [:create]

  def create
    @comment = current_user.comments.create(params[:comment])
    redirect_to :back
  end

end

app/controllers/links_controller.rb
class LinksController < ApplicationController

  def show
    @link = Link.find(params[:id])
    @comment = Comment.new
  end

  def new
    @link = Link.new
  end

  def create
   @link = Link.create(params[:link])
   if @link.errors.any?
     render "new"
   else
     redirect_to link_path(@link)
   end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def index
    @links = Link.paginate(page: params[:page], per_page: 10)
  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_filter :authenticate_user!, only: [:create]

  
  def create
    @vote = current_user.votes.where(:link_id => params[:vote][:link_id]).first
    @vote ||= current_user.votes.create(params[:vote])
    @vote.update_attributes(:up => params[:vote][:up])
    redirect_to :back
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/url_helper.rb
module UrlHelper
  def url_with_protocol(url)
    /^http/.match(url) ? url : "http://#{url}"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
    <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
  </head>

  <body>

<nav class="top-bar">
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to "Reddit on Rails", root_path %></a></h1>
    </li>
  </ul>
  <section class="top-bar-section">
    <ul class="right">
      <li class="divider"></li>
      <li><%= link_to "Browse Links", root_path %></li>
      <li class="divider"></li>
      <li><%= link_to "Submit Link", new_link_path %></li>
      <li class="divider"></li>
      <li><%= link_to "Sign Up", new_user_registration_path %></li>
      <li class="divider"></li>
      <li><%= link_to "Sign In", new_user_session_path %></li>
    </ul>
  </div>
</nav>

<div class="row">
  <div class="small-8 columns">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %></div>
  <div class="small-4 columns">
    <h2 class="subheader">Reddit On Rails</h2>
    This was a very simple weekend project to build a Reddit clone in Rails by Jesse Waites. Mostly stock Foundation 4 front-end. <%= link_to "Active Admin is installed and can be accessed here.", admin_root_path %> - login is admin@example.com, pw is "password". Site built in Rails version number 3.2. Anyone can see links and comments, but you must be logged in to upvote or downvote any of the submitted links. 
  </div>
</div>

    
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/links/create.html.erb
<h1>This is the create page</h1>

app/views/links/new.html.erb
<h3>Submit your link.</h3>


<%=form_for(@link) do |f|%>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>
      <ul>
      <% @link.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.text_field :title, placeholder: "Title..." %>
  <%= f.text_field :url, placeholder: "Enter YourLink.com" %>
  <%= f.submit %>
<%end%>

app/views/links/show.html.erb
<!-- <h1><%= @link.title %></h1> -->
<!-- <h4>Link: <%= link_to url_with_protocol(@link.url), :target => 'blank' %></h4> -->

<h2><%= link_to @link.title, @link.url %></h2>

<h2>Comments</h2>
<% @link.comments.each do |f| %>
  <p>
    <%= f.message %>
  </p>
<% end %>

<%= form_for(@comment) do |comment| %>
    <% if @comment.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this link from being saved:</h2>

          <ul>
            <% @comment.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= comment.label :message %><br />
      <%= comment.text_area :message, placehoder: "Add a comment" %>
      <%= comment.hidden_field :link_id, :value => @link.id %>
    </div>
    <div class="actions">
      <%= comment.submit %>
    </div>
<% end %>

app/views/pages/index.html.erb
<h2>Enjoy Yourself.</h2>

<% @links.each do |link| %>
<ul>
    <%= link_to link.title, link.url %>
    <br>
    
    <%= link.comments.count %><%= link_to ' Comments', link %>

    <i class="icon-arrow-up"></i><%= link_to 'Up Vote', votes_path({:vote => {:link_id => link.id, :up => true}}), :method => :post %>-
    <i class="icon-arrow-down"></i><%= link_to "Down Vote", votes_path(:vote => {:link_id => link.id, :up => false}), :method => :post %>
    <br>
    Total votes: <%=link.votes.where(up: true).count - link.votes.where(up: false).count%>
</ul>
<%end%>
<%= will_paginate @links %>